### ISSUE TITLE
.json model conversion question

### ISSUE THREAD

**Issue by nikolayrantsev** [keyth72/PedalNetRT#2]
Hi Keith, 
Thank you again for your effort, it's so interesting to dive into the world of amp modeling,

Please assist with the steps in order to play effect in real-time. 
I'm following the instruction, using the provided files https://github.com/keyth72/PedalNetRT/tree/master/data
Hers are the results of the otuput analysis:
![plot_diff_spectrogram](https://user-images.githubusercontent.com/59288233/95668023-ab204f80-0b76-11eb-89bf-996c526bec05.png)
![plot_signal_comparison_e2s_0 0134](https://user-images.githubusercontent.com/59288233/95668028-b3788a80-0b76-11eb-984b-f2cc618beab6.png)
![plot_Detail_signal_comparison_e2s_0 0134](https://user-images.githubusercontent.com/59288233/95668032-b70c1180-0b76-11eb-9366-e580ce51be87.png)
Then exectung the script to get .json model file. Convertion complete. Then uploading this model to SmartAmp or WaveNetVA -> noise, hum, etc. Size of the model is 1MB which is twice more than original. Original model works perfect: https://github.com/keyth72/PedalNetRT/blob/master/converted_model_ts9_ep1362.json
It seems to be the case with the conversion script process, this is what I'm exactly running:

```
python prepare_data.py data/ts9_test1_in_FP32.wav data/ts9_test1_out_FP32.wav
python test.py --model lightning_logs/version_3/checkpoints/epoch=1417.ckpt
python convert_pedalnet_to_wavenetva.py --model lightning_logs/version_3/checkpoints/epoch=1417.ckpt 
python plot_wav.py
```
[converted_model.json.zip](https://github.com/keyth72/PedalNetRT/files/5360448/converted_model.json.zip)

Could you please help with this?
Thank you!

**Comment by keyth72** [comment]
Looks like you're doing everything correctly, but I think the model is too large to run well in real time.  I updated the train.py script to use the same hyperparameters as the example model (which I should have done in the first place), so try retraining with the new params and see if that fixes the problem.

It's related to the WaveNet model dilations and repeat params. The one you trained has a layer pattern of "dilations": [1, 2, 4, 8, 16, 32, 64, 128, 1, 2, 4, 8, 16, 32, 64, 128, 1, 2, 4, 8, 16, 32, 64, 128], which is a 24 layer model. The one I updated with will have [1, 2, 4 ,8, 16, 32, 64, 128, 256, 512], which is a 10 layer model. You can view the hyperparams in the first part of the converted .json file.

It's kind of an art figuring out the best hyperparameters.  If you're interested in the technical details see the paper referenced in the readme Info.  Another big factor in real time processing is the "num_channels" param.  I've tried training with down to 5 layers with pretty impressive results, less accurate of course but much faster.

**Comment by nikolayrantsev** [comment]
Thank you so much, now works real-time, 
Yeah, it'll be interesting to play with the params configuration in order to achieve the best quality and real-time ability
