### ISSUE TITLE
Ability to specify model name?

### ISSUE THREAD

**Issue by mishushakov** [keyth72/PedalNetRT#3]
hey,
i'm currently building docker training environment to solve the reproducibility [issue](https://github.com/keyth72/SmartGuitarAmp/issues/5)

according to the doc, the name of a model is being generated after training is complete
is it possible to specify a name and a directory, eg. `python train.py --model=jtm45 --output=/models`?

otherwise, i could list the file(s) in the directory and export a environment variable
thanks

**Comment by keyth72** [comment]
Yes, check out this section from the pytorch lightning documentation:
"
Automatic saving
Lightning automatically saves a checkpoint for you in your current working directory, with the state of your last training epoch. This makes sure you can resume training in case it was interrupted.

To change the checkpoint path pass in:

# saves checkpoints to '/your/path/to/save/checkpoints' at every epoch end
trainer = Trainer(default_root_dir='/your/path/to/save/checkpoints')
"
Full doc here: https://pytorch-lightning.readthedocs.io/en/latest/weights_loading.html
