### ISSUE TITLE
When adding data training, the model can not be iterated in real time.

### ISSUE THREAD

**Issue by yudashuixiao1** [keyth72/PedalNetRT#6]
hIi,Keyth,
thank you for nice contribution.I come across a situation when the model was trained:
When adding data(such as 10minute） training, the model can not be iterated in real time. Always  Been in the .ckpt model state of  EPOCH = 0. Why is that? how to fix it ？ thank you very much!

**Comment by keyth72** [comment]
That’s odd, I haven’t seen that issue before. Do you see any errors in the console, and do you see the epoch number increasing in the console output? I’ve never tried training on 10 minute long data before, only up to 4 minutes long, so check if you get the same problem when using the default wav files in the data/ directory. If that works for you, it might be related to the wav files you’re using.

**Comment by yudashuixiao1** [comment]
> That’s odd, I haven’t seen that issue before. Do you see any errors in the console, and do you see the epoch number increasing in the console output? I’ve never tried training on 10 minute long data before, only up to 4 minutes long, so check if you get the same problem when using the default wav files in the data/ directory. If that works for you, it might be related to the wav files you’re using.

There are not any errors in the console. And the epoch number increasing kept outputing in the console.  I added data to your original data. Could it be that the added data does not match your format?  so weird.

**Comment by keyth72** [comment]
Yes that’s possible, if you try it with just the original data and it works then that’s the case. If you check out the YouTube link in the readme I explain a way to export the correct format using Reaper, you might be able to combine the files and render them that way, just be careful that no metadata is added. Or you could write a python script to append and export the combined data.
